# Generated by Django 5.1.4 on 2024-12-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('redirect_url', models.URLField()),
                ('description', models.TextField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='profiles.profile')),
            ],
        ),
    ]
