# Generated by Django 5.1.4 on 2024-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_jobsearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsearchhistory',
            name='location',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='jobsearchhistory',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobsearchhistory',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
